require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative './use_nativescript'

platform :ios, '10.0'

# use_frameworks!

# # workaround to avoid Xcode caching of Pods that requires
# # Product -> Clean Build Folder after new Cordova plugins installed
# # Requires CocoaPods 1.6 or newer
# install! 'cocoapods', :disable_input_output_paths => true

# def capacitor_pods
#   pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
#   pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
# end

target 'NativescriptRuntimeExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-nativescript-runtime', :path => '../..'

  use_nativescript({
    :path_to_project => path_to_project = Dir.entries(__dir__).find {|entry| entry.end_with? ".xcodeproj" },
    :projectTargetName => 'NativescriptRuntimeExample'
  })

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!()
  # post_install do |installer|
  #   react_native_post_install(installer)
  # end
end
